"""Runtime configuration for the disk monitoring application."""

REFRESH_INTERVAL_SECONDS = 2.0
IO_SAMPLE_INTERVAL_SECONDS = 1.0
LOG_FILE = "logs/disk_monitor.jsonl"
WARNING_DISK_USAGE_PERCENT = 80.0
CRITICAL_DISK_USAGE_PERCENT = 95.0
SHOW_CONSOLE_OUTPUT = True

TOP_PROCESS_LIMIT = 5
MINIMUM_PROCESS_IO_BYTES = 1

HISTORY_FILE = "logs/metrics_history.jsonl"
EVENT_TIMELINE_FILE = "logs/event_timeline.jsonl"
HISTORY_RETENTION_RECORDS = 10_000
EVENT_RETENTION_RECORDS = 5_000
SPIKE_USAGE_DELTA_PERCENT = 20.0
SPIKE_IO_MULTIPLIER = 3.0
SPIKE_IO_MIN_BYTES_PER_SECOND = 1_048_576.0

ROOT_CAUSE_PROCESS_SHARE_PERCENT = 50.0
ROOT_CAUSE_MIN_PROCESS_RATE_BYTES_PER_SECOND = 1.0
ROOT_CAUSE_SUSTAINED_SAMPLES = 3

PROCESS_PROFILE_HISTORY_SAMPLES = 20
PROCESS_ANOMALY_MIN_BASELINE_SAMPLES = 3
PROCESS_ANOMALY_RATE_MULTIPLIER = 3.0
PROCESS_ANOMALY_SHARE_DELTA_PERCENT = 25.0
PROCESS_ANOMALY_MIN_RATE_BYTES_PER_SECOND = 262_144.0
RUNAWAY_PROCESS_SAMPLES = 3
RUNAWAY_PROCESS_SHARE_PERCENT = 60.0
RUNAWAY_PROCESS_MIN_RATE_BYTES_PER_SECOND = 1_048_576.0

RECOMMENDATION_MAX_ITEMS = 5
RECOMMENDATION_MIN_ROOT_CAUSE_CONFIDENCE = 55.0
RECOMMENDATION_HIGH_IMPACT_SCORE = 70.0
RECOMMENDATION_MEDIUM_IMPACT_SCORE = 40.0

AUTO_OPTIMIZATION_ENABLED = False
AUTO_OPTIMIZATION_MAX_ACTIONS = 1
AUTO_OPTIMIZATION_MIN_IMPACT_SCORE = 65.0
AUTO_OPTIMIZATION_PRIORITY_STEP = 5
OPTIMIZATION_JOURNAL_FILE = "logs/optimization_journal.jsonl"
AUTO_OPTIMIZATION_DENYLIST = (
    "system", "systemd", "init", "kernel_task", "launchd",
    "smss.exe", "csrss.exe", "wininit.exe", "services.exe",
    "lsass.exe", "winlogon.exe",
)

# M8 alerting and notification defaults.
ALERT_FILE = "logs/alerts.jsonl"
ALERT_RETENTION_RECORDS = 5_000
ALERT_COOLDOWN_SECONDS = 300.0
ALERT_MIN_RECOMMENDATION_PRIORITY_SCORE = 65.0
ALERT_RECOVERY_ENABLED = True

REFRESH_INTERVAL = REFRESH_INTERVAL_SECONDS
